# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-11-22 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sex',
            new_name='date_sex',
        ),
    ]
