# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-11-06 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('min_distance', models.IntegerField(default=1)),
                ('max_distance', models.IntegerField(default=10)),
                ('max_data_age', models.IntegerField(default=18)),
                ('min_data_age', models.IntegerField(default=40)),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=8)),
                ('virbation', models.BooleanField(default=True)),
                ('friend_only', models.BooleanField(default=False)),
                ('auto_play', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
